

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Stratis.DevEx.Ethereum;
//
//    var packageJsonFile = PackageJsonFile.FromJson(jsonString);

namespace Stratis.DevEx.Ethereum.SolidityCompilerIO
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PackageJsonFile
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public string Version { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("main", NullValueHandling = NullValueHandling.Ignore)]
        public string Main { get; set; }

        [JsonProperty("scripts", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> Scripts { get; set; }

        [JsonProperty("author", NullValueHandling = NullValueHandling.Ignore)]
        public string Author { get; set; }

        [JsonProperty("license", NullValueHandling = NullValueHandling.Ignore)]
        public string License { get; set; }

        [JsonProperty("devDependencies", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> DevDependencies { get; set; }

        [JsonProperty("dependencies", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> Dependencies { get; set; }
    }
    
    public partial class PackageJsonFile
    {
        public static PackageJsonFile Parse(string json) => JsonConvert.DeserializeObject<PackageJsonFile>(json, Stratis.DevEx.Ethereum.SolidityCompilerIO.PackageJsonConverter.Settings);
        public static string ToJson(PackageJsonFile self) => JsonConvert.SerializeObject(self, Stratis.DevEx.Ethereum.SolidityCompilerIO.PackageJsonConverter.Settings);
    }

    public static class PackageJsonConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}



   
