//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stratis.CodeAnalysis.Cs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stratis.CodeAnalysis.Cs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart contract classes cannot be declared inside a namespace..
        /// </summary>
        internal static string SC0001_Description {
            get {
                return ResourceManager.GetString("SC0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smart contract class cannot be declared inside the namespace {0}..
        /// </summary>
        internal static string SC0001_MessageFormat {
            get {
                return ResourceManager.GetString("SC0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace declaration not allowed for smart contract class..
        /// </summary>
        internal static string SC0001_Title {
            get {
                return ResourceManager.GetString("SC0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types from this namespace cannot be used in smart contract code..
        /// </summary>
        internal static string SC0002_Description {
            get {
                return ResourceManager.GetString("SC0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types from namespace {0} cannot be used in smart contract code..
        /// </summary>
        internal static string SC0002_MessageFormat {
            get {
                return ResourceManager.GetString("SC0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types from this namespace cannot be used in smart contract code..
        /// </summary>
        internal static string SC0002_Title {
            get {
                return ResourceManager.GetString("SC0002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes in smart contract code must inherit from Stratis.SmartContracts.SmartContract..
        /// </summary>
        internal static string SC0003_Description {
            get {
                return ResourceManager.GetString("SC0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} must inherit from class Stratis.SmartContracts.SmartContract.
        /// </summary>
        internal static string SC0003_MessageFormat {
            get {
                return ResourceManager.GetString("SC0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart contract class must inherit from type Stratis.SmartContracts.SmartContract..
        /// </summary>
        internal static string SC0003_Title {
            get {
                return ResourceManager.GetString("SC0003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first parameter in a smart contract constructor must be of type ISmartContractState..
        /// </summary>
        internal static string SC0004_Description {
            get {
                return ResourceManager.GetString("SC0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} must be of type ISmartContractState..
        /// </summary>
        internal static string SC0004_MessageFormat {
            get {
                return ResourceManager.GetString("SC0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First parameter in a smart contract constructor must be of type ISmartContractState..
        /// </summary>
        internal static string SC0004_Title {
            get {
                return ResourceManager.GetString("SC0004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object creation of a reference type is not allowed in smart contract code..
        /// </summary>
        internal static string SC0005_Description {
            get {
                return ResourceManager.GetString("SC0005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new {0} object cannot be created here..
        /// </summary>
        internal static string SC0005_MessageFormat {
            get {
                return ResourceManager.GetString("SC0005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object creation of a reference type is not allowed in smart contract code..
        /// </summary>
        internal static string SC0005_Title {
            get {
                return ResourceManager.GetString("SC0005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-const field declarations are not allowed in smart contract classes..
        /// </summary>
        internal static string SC0006_Description {
            get {
                return ResourceManager.GetString("SC0006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-const field declaration cannot be made in the class {0}..
        /// </summary>
        internal static string SC0006_MessageFormat {
            get {
                return ResourceManager.GetString("SC0006_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-const field declarations are not allowed in smart contract classes.
        /// </summary>
        internal static string SC0006_Title {
            get {
                return ResourceManager.GetString("SC0006_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only certain variable types can be used in smart contract code..
        /// </summary>
        internal static string SC0007_Description {
            get {
                return ResourceManager.GetString("SC0007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot declare a variable of type {0} here..
        /// </summary>
        internal static string SC0007_MessageFormat {
            get {
                return ResourceManager.GetString("SC0007_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable declaration of this type not allowed in smart contract code..
        /// </summary>
        internal static string SC0007_Title {
            get {
                return ResourceManager.GetString("SC0007_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only certain types and members can be used in smart contract code.
        /// </summary>
        internal static string SC0008_Description {
            get {
                return ResourceManager.GetString("SC0008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} from type {1} cannot be used here..
        /// </summary>
        internal static string SC0008_MessageFormat {
            get {
                return ResourceManager.GetString("SC0008_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property cannot be used in smart contract code..
        /// </summary>
        internal static string SC0008_Title {
            get {
                return ResourceManager.GetString("SC0008_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method cannot be used in smart contract code..
        /// </summary>
        internal static string SC0009_Description {
            get {
                return ResourceManager.GetString("SC0009_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} from type {1} cannot be used here..
        /// </summary>
        internal static string SC0009_MessageFormat {
            get {
                return ResourceManager.GetString("SC0009_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method cannot be used in smart contract code..
        /// </summary>
        internal static string SC0009_Title {
            get {
                return ResourceManager.GetString("SC0009_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assert condition should be derived from input or state.
        /// </summary>
        internal static string SC0010_Description {
            get {
                return ResourceManager.GetString("SC0010_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert condition will always evaluate to {0}.
        /// </summary>
        internal static string SC0010_MessageFormat {
            get {
                return ResourceManager.GetString("SC0010_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert condition should not be constant.
        /// </summary>
        internal static string SC0010_Title {
            get {
                return ResourceManager.GetString("SC0010_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom assert message should be used, as this can be parsed to identify reason for failure.
        /// </summary>
        internal static string SC0011_Description {
            get {
                return ResourceManager.GetString("SC0011_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert should contain custom message that indicates exact reason for failure.
        /// </summary>
        internal static string SC0011_MessageFormat {
            get {
                return ResourceManager.GetString("SC0011_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert should contain custom message.
        /// </summary>
        internal static string SC0011_Title {
            get {
                return ResourceManager.GetString("SC0011_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert message should not be empty, as this can be parsed to identify reason for failure.
        /// </summary>
        internal static string SC0012_Description {
            get {
                return ResourceManager.GetString("SC0012_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert message should indicate exact reason for failure.
        /// </summary>
        internal static string SC0012_MessageFormat {
            get {
                return ResourceManager.GetString("SC0012_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert message should not be empty.
        /// </summary>
        internal static string SC0012_Title {
            get {
                return ResourceManager.GetString("SC0012_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type cannot be used in smart contract code..
        /// </summary>
        internal static string SC0013_Description {
            get {
                return ResourceManager.GetString("SC0013_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} cannot be used in smart contract code..
        /// </summary>
        internal static string SC0013_MessageFormat {
            get {
                return ResourceManager.GetString("SC0013_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type cannot be used in smart contract code..
        /// </summary>
        internal static string SC0013_Title {
            get {
                return ResourceManager.GetString("SC0013_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type cannot be used as a smart contract method return type or parameter type..
        /// </summary>
        internal static string SC0014_Description {
            get {
                return ResourceManager.GetString("SC0014_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} cannot be used as a smart contract method return type or parameter type..
        /// </summary>
        internal static string SC0014_MessageFormat {
            get {
                return ResourceManager.GetString("SC0014_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type cannot be used as a smart contract method return type or parameter type..
        /// </summary>
        internal static string SC0014_Title {
            get {
                return ResourceManager.GetString("SC0014_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smart contract class cannnot declare a destructor or finalizer..
        /// </summary>
        internal static string SC0015_Description {
            get {
                return ResourceManager.GetString("SC0015_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The smart contract class {0} cannot declare a destructor or finalizer..
        /// </summary>
        internal static string SC0015_MessageFormat {
            get {
                return ResourceManager.GetString("SC0015_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smart contract class cannnot declare a destructor or finalizer..
        /// </summary>
        internal static string SC0015_Title {
            get {
                return ResourceManager.GetString("SC0015_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling with try/catch blocks is not allowed in smart contract code due to non-deterministic behaviour..
        /// </summary>
        internal static string SC0016_Description {
            get {
                return ResourceManager.GetString("SC0016_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling with try/catch blocks not allowed in smart contract code..
        /// </summary>
        internal static string SC0016_MessageFormat {
            get {
                return ResourceManager.GetString("SC0016_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling with try/catch blocks not allowed in smart contract code..
        /// </summary>
        internal static string SC0016_Title {
            get {
                return ResourceManager.GetString("SC0016_Title", resourceCulture);
            }
        }
    }
}
