name: Build StratisEVM extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: src\Stratis.DevEx.sln
      VSTEST_CONNECTION_TIMEOUT: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Update extension version
        run: |
          (Get-Content -Path .\src\Stratis.VS.StratisEVM\source.extension.vsixmanifest) |
            ForEach-Object {$_ -Replace '0.1.5.0', '0.1.5.${{ github.run_number }}'} |
              Set-Content -Path .\src\Stratis.VS.StratisEVM\source.extension.vsixmanifest
          (Get-Content -Path .\src\Stratis.VS.StratisEVM\Properties\AssemblyInfo.cs) |
            ForEach-Object {$_ -Replace '0.1.5.0', '0.1.5.${{ github.run_number }}'} |
              Set-Content -Path .\src\Stratis.VS.StratisEVM\Properties\AssemblyInfo.cs
          (Get-Content -Path .\src\Stratis.VS.StratisEVM\StratisEVMPackage.cs) |
            ForEach-Object {$_ -Replace '0.1.5.0', '0.1.5.${{ github.run_number }}'} |
              Set-Content -Path .\src\Stratis.VS.StratisEVM\StratisEVMPackage.cs
      - name: Package restore
        run: nuget restore "${{ env.Solution_Name }}"
      - name: Build
        run: msbuild ".\src\Stratis.VS.StratisEVM\Stratis.VS.StratisEVM.csproj" /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
      - uses: actions/upload-artifact@v4
        with:
          name: Stratis.VS.StratisEVM.vsix
          path: .\src\Stratis.VS.StratisEVM\bin\Release\Stratis.VS.StratisEVM.vsix
      - name: Push Stratis.VS.StratisEVM VSIX to MyGet dev feed
        run: 'curl -X POST --verbose --data-binary ".\src\Stratis.VS.StratisEVM\bin\Release\Stratis.VS.StratisEVM.vsix" -H "X-NuGet-ApiKey: ${{ secrets.MYGET_TOKEN }}" https://www.myget.org/F/stratisdevex/vsix/upload'