name: Publish packages to MyGet dev feed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: src\Stratis.DevEx.sln
      CodeAnalysis_Cs_Project_Path: "src\\Stratis.CodeAnalysis.Cs\\Stratis.CodeAnalysis.Cs.Package\\Stratis.CodeAnalysis.Cs.Package.csproj"
      CodeAnalysis_Cs_Test_Project_Path: "tests\\Stratis.CodeAnalysis.Cs.Test\\Stratis.CodeAnalysis.Cs.Test.csproj"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install .NET 6.0 workload
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore the Stratis.DevEx solution
      run: dotnet restore "${{ env.Solution_Name }}"  /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
            
    - name: Execute Stratis.CodeAnalysis.Cs unit tests
      run: dotnet test "${{ env.CodeAnalysis_Cs_Test_Project_Path }}" -l "console;verbosity=detailed"
    
    - name: Get Stratis.CodeAnalysis.Cs base package version
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        xpath: //PropertyGroup//PackageVersion
        file: "${{ env.CodeAnalysis_Cs_Project_Path }}"
    
    - name: Get git commit SHA
      id: git_sha
      run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash
      
    - name: Set Stratis.CodeAnalysis.Cs CI package version
      id: ci_version
      run: echo "CI_VERSION=ci${{ env.GIT_SHA }}" >> $env:GITHUB_ENV
    
    - name: Pack Stratis.CodeAnalysis.Cs package
      run: dotnet pack ${{ env.CodeAnalysis_Cs_Project_Path }} --configuration Debug --version-suffix ${{ env.CI_VERSION }} --output .

    - name: Push Stratis.CodeAnalysis.Cs package to dev feed
      run: dotnet nuget push .\Stratis.CodeAnalysis.${{ env.CI_VERSION }}.nupkg --source https://www.myget.org/F/stratisdevex/api/v2/package --api-key ${{ env.MYGET_TOKEN }}
      env:
        MYGET_TOKEN: ${{ secrets.MYGET_TOKEN }}
