name: Build StratisEVM extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Add nuget to PATH
        uses: nuget/setup-nuget@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Update version
        run: |
          (Get-Content -Path .\src\Stratis.VS.StratisEVM\source.extension.vsixmanifest) |
            ForEach-Object {$_ -Replace '0.1.5.0', '0.1.5.${{ github.run_number }}'} |
              Set-Content -Path .\src\Stratis.VS.StratisEVM\source.extension.vsixmanifest
          (Get-Content -Path .\src\Stratis.VS.StratisEVM\Properties\AssemblyInfo.cs) |
            ForEach-Object {$_ -Replace '0.1.5.0', '0.1.5.${{ github.run_number }}'} |
              Set-Content -Path .\src\Stratis.VS.StratisEVM\Properties\AssemblyInfo.cs
          (Get-Content -Path .\src\Stratis.VS.StratisEVM\StratisEVMPackage.cs) |
            ForEach-Object {$_ -Replace '0.1.5.0', '0.1.5.${{ github.run_number }}'} |
              Set-Content -Path .\src\Stratis.VS.StratisEVM\StratisEVMPackage.cs
      - name: Restore
        run: nuget restore
      - name: Build
        run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
      - uses: actions/upload-artifact@v2
        with:
          name: Stratis.VS.StratisEVM.vsix
          path: .\src\Stratis.VS.StratisEVM\bin\Release\Stratis.VS.StratisEVM.vsix